# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"
languageCode = "fr"
defaultContentLanguage = "fr"
theme = "rero-hugo-bootstrap"
preserveTaxonomyNames = true

# Title of your site
title = "Blog RERO 21"

# Pagination
paginate = 4
paginatePath = "page"

# RSS
rssLimit = 20

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  tag = "tags"
  category = "categories"

[frontmatter]
  date = ["date", "publishDate"]
  lastmod = ["lastmod"]
  publishDate = ["publishDate", "date"]


# Google analytics
# googleAnalytics = "UA-47268287-3"


[languages.fr]
  languageName = "Français"

  # Replace the default footer message with a localized message
  copyright = "© copyright 2021 RERO"
  
  [[languages.fr.menu.main]]
    name = "RERO ILS"
    weight = 1
  [[languages.fr.menu.main]]
    url = "/mef/"
    name = "MEF"
    weight = 2
  [[languages.fr.menu.main]]
    url = "/about/"
    name = "À propos"
    weight = 3
  [[languages.fr.menu.main]]
    url = "/resources/"
    name = "Ressources"
    weight = 4
  [[languages.fr.menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 5
  [[languages.fr.menu.main]]
    url = "/reroils/reroils/"
    name = "Présentation"
    parent = "RERO ILS"
    weight = 1
  [[languages.fr.menu.main]]
    url = "/reroils/features/"
    name = "Fonctionnalités"
    parent = "RERO ILS"
    weight = 2
  [[languages.fr.menu.main]]
    url = "/reroils/early_adopters/"
    name = "Early adopters"
    parent = "RERO ILS"
    weight = 3
  [[languages.fr.menu.main]]
    url = "/reroils/pricing/"
    name = "Tarifs"
    parent = "RERO ILS"
    weight = 4
  [[languages.fr.menu.main]]
    url = "/reroils/migration2021/"
    name = "Migration 2021"
    parent = "RERO ILS"
    weight = 5

[languages.en]
  languageName = "English"

  # Replace the default footer message with a localized message
  copyright = "© copyright 2021 RERO"
  
  [[languages.en.menu.main]]
    name = "RERO ILS"
    weight = 1
  [[languages.en.menu.main]]
    url = "/mef/"
    name = "MEF"
    weight = 2
  [[languages.en.menu.main]]
    url = "/about/"
    name = "About"
    weight = 3
  [[languages.en.menu.main]]
    url = "/resources/"
    name = "Resources"
    weight = 4
  [[languages.en.menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 5
  [[languages.en.menu.main]]
    url = "/reroils/reroils/"
    name = "Presentation"
    parent = "RERO ILS"
    weight = 1
  [[languages.en.menu.main]]
    url = "/reroils/features/"
    name = "Features"
    parent = "RERO ILS"
    weight = 2
  [[languages.en.menu.main]]
    url = "/reroils/early_adopters/"
    name = "Early adopters"
    parent = "RERO ILS"
    weight = 3
  [[languages.en.menu.main]]
    url = "/reroils/pricing/"
    name = "Pricing"
    parent = "RERO ILS"
    weight = 4
  [[languages.en.menu.main]]
    url = "/reroils/migration2021/"
    name = "Migration 2021"
    parent = "RERO ILS"
    weight = 5

[languages.de]
  languageName = "Deutsch"

  # Replace the default footer message with a localized message
  copyright = "© copyright 2021 RERO"

  [[languages.de.menu.main]]
    name = "RERO ILS"
    weight = 1
  [[languages.de.menu.main]]
    url = "/mef/"
    name = "MEF"
    weight = 2
  [[languages.de.menu.main]]
    url = "/about/"
    name = "Über das Projekt"
    weight = 3
  [[languages.de.menu.main]]
    url = "/resources/"
    name = "Ressourcen"
    weight = 4
  [[languages.de.menu.main]]
    url = "/contact/"
    name = "Kontakt"
    weight = 5
  [[languages.de.menu.main]]
    url = "/reroils/reroils/"
    name = "Presentation"
    parent = "RERO ILS"
    weight = 1
  [[languages.de.menu.main]]
    url = "/reroils/features/"
    name = "Funktionalitäten"
    parent = "RERO ILS"
    weight = 2
  [[languages.de.menu.main]]
    url = "/reroils/early_adopters/"
    name = "Early adopters"
    parent = "RERO ILS"
    weight = 3
  [[languages.de.menu.main]]
    url = "/reroils/pricing/"
    name = "Tarife"
    parent = "RERO ILS"
    weight = 4
  [[languages.de.menu.main]]
    url = "/reroils/migration2021/"
    name = "Migration 2021"
    parent = "RERO ILS"
    weight = 5

# Links format

[permalinks]
  post = "/:filename/"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["post"]

  # Default author
  # author = "RERO"

  # Date format (default: Jan 2, 2006)
  date_format = "2006-01-02"

  # Display post summaries instead of content in list templates (default: true)
  # truncate = false

  # Display social sharing buttons (default: true)
  # share = true 

  [params.sidebar]
    # Whether to show the recent posts or not (default: true)
    # showRecent = false

    # Whether to show the taxonomies or not (default: true)
    # showTaxonomy = false

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 5
